# Generated by Django 2.0.7 on 2018-08-02 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import picklefield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('started', models.DateTimeField(db_index=True, null=True)),
                ('ended', models.DateTimeField(db_index=True, null=True)),
                ('output', models.TextField(default='')),
                ('traceback', models.TextField(default='')),
            ],
            options={
                'ordering': ('started',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_ip', models.GenericIPAddressField(null=True)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('spooled', models.DateTimeField(db_index=True, null=True)),
                ('data', picklefield.fields.PickledObjectField(editable=False, null=True)),
                ('callback', models.CharField(db_index=True, max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Spooled'), (2, 'Started'), (3, 'Success'), (4, 'Retrying'), (5, 'Failure')], db_index=True, default=0)),
                ('max_executions', models.IntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_uwsgi_spooler.Task')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='execution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_uwsgi_spooler.Task'),
        ),
    ]
