# Generated by Django 2.0.7 on 2018-08-01 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import picklefield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_ip', models.GenericIPAddressField(null=True)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('spooled', models.DateTimeField(db_index=True, null=True)),
                ('started', models.DateTimeField(db_index=True, null=True)),
                ('ended', models.DateTimeField(db_index=True, null=True)),
                ('data', picklefield.fields.PickledObjectField(editable=False, null=True)),
                ('callback', models.CharField(db_index=True, max_length=255)),
                ('output', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Spooled'), (2, 'Started'), (3, 'Success'), (4, 'Error')], db_index=True, default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_uwsgi_spooler.Task')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
