# Generated by Django 2.0.7 on 2018-08-01 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import picklefield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_ip', models.GenericIPAddressField(null=True)),
                ('creation_datetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('spool_datetime', models.DateTimeField(db_index=True, null=True)),
                ('start_datetime', models.DateTimeField(db_index=True, null=True)),
                ('end_datetime', models.DateTimeField(db_index=True, null=True)),
                ('env', picklefield.fields.PickledObjectField(editable=False, null=True)),
                ('callback_name', models.CharField(db_index=True, max_length=255)),
                ('progress', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=100)),
                ('output', models.TextField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('started', 'Started'), ('success', 'Success'), ('error', 'Error')], db_index=True, default='created', max_length=15)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_uwsgi_spooler.Task')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('creation_datetime',),
            },
        ),
    ]
