# Generated by Django 2.0.7 on 2018-08-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_uwsgi_spooler', '0002_auto_20180812_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='execution',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Spooled'), (2, 'Started'), (3, 'Success'), (4, 'Retrying'), (5, 'Failure')], db_index=True, default=0, editable=False),
        ),
    ]
